# frozen_string_literal: true

require 'rake/clean'

WARNING = <<-WGET
   WARNING: you may not have wget installed, you could just download
   the correct version of propane-examples (see EXAMPLES vendors directory)
WGET
SOUND = 'sound.zip'
PROCESSING_GITHUB = 'https://github.com/processing'
PROPANE_EXAMPLES = 'https://github.com/ruby-processing/propane-examples'
VIDEO = 'video.zip'
DOWNLOAD = 'releases/download/latest'
EXAMPLES = '3.5'
HOME_DIR = ENV['HOME']
LIBRARY = File.join(HOME_DIR, '.propane', 'libraries')
MAC_OR_LINUX = /linux|mac|darwin/.match?(RbConfig::CONFIG['host_os'])

CLOBBER.include(EXAMPLES, SOUND, VIDEO)

desc 'download, and copy propane examples'
task default: [:download_and_copy_samples]

desc 'download and copy examples to user home'
task download_and_copy_samples: %i[download_examples copy_examples]

task :download_examples
file_name = MAC_OR_LINUX.nil? ? "#{EXAMPLES}.zip" : "#{EXAMPLES}.tar.gz"
wget_base = ['wget', PROPANE_EXAMPLES].join(' ')
wget_string = [wget_base, 'archive', file_name].join('/')
file file_name do
  begin
    sh wget_string
  rescue StandardError
    warn(WARNING)
  end
end

desc 'download and copy sound library to ~/.propane'
task download_and_copy_sound: %i[init_dir download_sound copy_sound clobber]

desc 'download and copy video library to ~/.propane'
task download_and_copy_video: %i[init_dir download_video copy_video clobber]

desc 'download sound library'
task :download_sound do
  wget_base = ['wget', PROCESSING_GITHUB].join(' ')
  wget_string = [wget_base, 'processing-sound', DOWNLOAD, SOUND].join('/')
  begin
    sh wget_string
  rescue StandardError
    warn(WARNING)
  end
end

desc 'initialize ~/.propane directories'
task :init_dir do
  FileUtils.mkdir_p LIBRARY unless File.exist? LIBRARY
end

desc 'download video library'
task :download_video do
  wget_base = ['wget', PROCESSING_GITHUB].join(' ')
  wget_string = [wget_base, 'processing-video', DOWNLOAD, VIDEO].join('/')
  begin
    sh wget_string
  rescue StandardError
    warn(WARNING)
  end
end

desc 'copy examples'
task copy_examples: file_name do
  if MAC_OR_LINUX.nil?
    sh "unzip #{EXAMPLES}.zip"
  else
    sh "tar xzvf #{EXAMPLES}.tar.gz"
  end
  sh "rm -r #{HOME_DIR}/propane_samples" if File.exist? "#{HOME_DIR}/propane_samples"
  sh "cp -r propane-examples-#{EXAMPLES} #{HOME_DIR}/propane_samples"
  sh "rm -r propane-examples-#{EXAMPLES}"
end

desc 'copy sound library'
task copy_sound: SOUND do
  sh "unzip #{SOUND}"
  sh "rm -r #{LIBRARY}/sound" if File.exist? "#{LIBRARY}/sound"
  sh "cp -r sound #{LIBRARY}"
  sh 'rm -r sound'
end

desc 'copy video library'
task copy_video: VIDEO do
  sh "unzip #{VIDEO}"
  sh "rm -r #{LIBRARY}/video" if File.exist? "#{LIBRARY}/video"
  sh "cp -r video #{LIBRARY}"
  sh 'rm -r video'
end
